language: go

go:
  - 1.5

install:
  - go get github.com/Masterminds/glide
  - (cd $GOPATH/src/github.com/Masterminds/glide && make bootstrap && make build)
  - GO15VENDOREXPERIMENT=1 glide install

script: GO15VENDOREXPERIMENT=1 go test -v
