language: go

sudo: false

go:
  - tip
  - stable

matrix:
  allow_failures:
    - go: tip

services:
  - mysql
  - postgresql

install:
  - go get github.com/onsi/ginkgo/ginkgo

env:
  - DB=mysql
  - DB=postgres

before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE y_test;" -uroot; fi
  - if [[ "$DB" == "postgres" ]]; then psql -c "CREATE DATABASE y_test;" -U postgres; fi

script: ginkgo -v
