language: go

go:
  - 1.5
  - tip

install:
  - go get github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && make bootstrap && make build
  - glide install

script: GO15VENDOREXPERIMENT=1 go test -v
